import { Component, OnInit, inject } from '@angular/core';
import { ApiService } from '../core/api.service';

interface Gate { name: string; status: string; severity: string; requirement: string; result: string; reviewer: string; timestamp: string; }
interface Environment { name: string; state: string; date: string; build: string; tone: string; }

@Component({
  standalone: true,
  selector: 'app-security',
  styleUrl: './security.component.scss',
  template: `
    <div class="page dashboard-page">
      <div class="page-header dashboard-header"><div><p class="eyebrow">Deployment governance</p><h1>Security Deployment Gates</h1><p class="subtitle">Review security controls, exceptions, approvals, and deployment readiness across environments.</p><div class="dashboard-context"><span><span class="material-icons">domain</span>Northstar Enterprise</span><span><span class="material-icons">schedule</span>Release train Â· 2026.09</span><span><span class="material-icons">update</span>{{ error ? 'Local operational snapshot' : 'Live operational data' }}</span></div></div><button class="btn btn-secondary" [disabled]="loading" (click)="load()"><span class="material-icons">refresh</span>{{ loading ? 'Refreshingâ€¦' : 'Refresh data' }}</button></div>
      @if (loading) { <span class="dashboard-sync-status">Refreshing deployment evidenceâ€¦</span> } @else if (error) { <span class="dashboard-sync-status dashboard-sync-error">Showing governance snapshot Â· live metrics unavailable</span> }
      <section class="readiness-banner success-banner"><span class="banner-icon material-icons">verified_user</span><div><strong>All Security Gates Passed</strong><p>No critical vulnerabilities Â· Required approvals complete Â· Validation successful</p></div><div class="confidence"><span>Deployment confidence</span><strong>94%</strong></div><span class="banner-action">Ready to promote to next environment <span class="material-icons">arrow_forward</span></span></section>
      <section class="panel pipeline-panel"><div class="panel-title"><div><p class="eyebrow">PROMOTION WORKFLOW</p><h2>Deployment Pipeline</h2></div><span class="badge badge-success">Release 2026.09.17</span></div><div class="pipeline">@for (stage of stages; track stage.name; let last = $last) {<div class="pipeline-stage"><span class="stage-status" [class]="stage.tone"><span class="material-icons">{{stage.icon}}</span></span><strong>{{stage.name}}</strong>@if (!last) {<span class="pipeline-arrow">â†’</span>}</div>}</div><div class="pipeline-legend"><span><i class="ready"></i> Passed / Ready</span><span><i class="review"></i> Review Required</span><span><i class="blocked"></i> Blocked</span><span><i class="pending"></i> Pending</span></div></section>
      <section class="kpi-grid">@for (item of kpis; track item.label) {<article class="metric-card kpi-card"><div class="kpi-top"><span class="metric-label">{{item.label}}</span><span class="material-icons kpi-icon" [class]="item.tone">{{item.icon}}</span></div><strong class="metric-value">{{item.value}}</strong><span class="metric-note" [class]="item.tone">{{item.note}}</span></article>}</section>
      <section class="panel"><div class="panel-title"><div><p class="eyebrow">MANDATORY CONTROLS</p><h2>Security Gate Checklist</h2></div><span class="badge badge-success">12 / 12 evaluated</span></div><div class="table-wrap"><table class="data-table gate-table"><thead><tr><th>Check name</th><th>Status</th><th>Severity</th><th>Required</th><th>Result</th><th>Reviewer</th><th>Timestamp</th></tr></thead><tbody>@for (gate of gates; track gate.name) {<tr><td><strong>{{gate.name}}</strong></td><td><span class="status-pill" [class]="gate.status.toLowerCase().replace(' ', '-')"><span class="status-dot"></span>{{gate.status}}</span></td><td><span class="badge" [class]="'badge-' + gate.severity.toLowerCase()">{{gate.severity}}</span></td><td>{{gate.requirement}}</td><td class="result">{{gate.result}}</td><td>{{gate.reviewer}}</td><td class="muted-cell">{{gate.timestamp}}</td></tr>}</tbody></table></div></section>
      <section class="two-column section-gap"><div class="panel"><div class="panel-title"><div><p class="eyebrow">STOP THE LINE</p><h2>Critical Blockers</h2></div><span class="badge badge-critical">Deployment Blocked</span></div><p class="panel-description">Vulnerabilities and policy violations that must never be ignored.</p><ul class="blocker-list">@for (blocker of blockers; track blocker.name) {<li><span class="material-icons">gpp_bad</span><div><strong>{{blocker.name}}</strong><span>{{blocker.reason}}</span></div><b>{{blocker.count}}</b></li>}</ul></div><div class="panel score-panel"><div class="panel-title"><div><p class="eyebrow">RISK POSTURE</p><h2>Security Scorecard</h2></div><strong class="overall-score">92<span>/100</span></strong></div><div class="score-list">@for (score of scores; track score.label) {<div><div class="score-label"><span>{{score.label}}</span><strong>{{score.value}}</strong></div><div class="progress"><span [style.width.%]="score.value"></span></div></div>}</div></div></section>
      <section class="panel section-gap"><div class="panel-title"><div><p class="eyebrow">GOVERNED RISK ACCEPTANCE</p><h2>Security Exceptions</h2></div><button class="btn btn-secondary btn-small">Review requests</button></div><div class="exception-summary"><div><strong>7</strong><span>Total active exceptions</span></div><div class="warning-stat"><strong>2</strong><span>Expired exceptions</span></div><div><strong>3</strong><span>Pending requests</span></div></div><div class="table-wrap"><table class="data-table"><thead><tr><th>Finding ID</th><th>Application</th><th>Severity</th><th>Reason</th><th>Approved by</th><th>Expiration</th><th>Status</th></tr></thead><tbody>@for (exception of exceptions; track exception.id) {<tr><td><strong>{{exception.id}}</strong></td><td>{{exception.app}}</td><td><span class="badge" [class]="'badge-' + exception.severity.toLowerCase()">{{exception.severity}}</span></td><td>{{exception.reason}}</td><td>{{exception.approved}}</td><td>{{exception.expiration}}</td><td><span class="status-pill success">{{exception.status}}</span></td></tr>}</tbody></table></div></section>
      <section class="section-gap"><div class="section-heading"><div><p class="eyebrow">PROMOTION TARGETS</p><h2>Environment Deployment Status</h2></div></div><div class="environment-grid">@for (environment of environments; track environment.name) {<article class="panel environment-card"><div class="environment-title"><h3>{{environment.name}}</h3><span class="environment-state" [class]="environment.tone"><span class="status-dot"></span>{{environment.state}}</span></div><div class="environment-meta"><span>Deployment date<strong>{{environment.date}}</strong></span><span>Build number<strong>{{environment.build}}</strong></span></div></article>}</div></section>
      <section class="two-column section-gap"><div class="panel"><div class="panel-title"><div><p class="eyebrow">QUALITY EVIDENCE</p><h2>Validation Results</h2></div><span class="badge badge-success">All passing</span></div><div class="validation-grid">@for (validation of validations; track validation.label) {<div class="validation-item"><div><span>{{validation.label}}</span><strong>{{validation.value}}%</strong></div><div class="progress"><span [style.width.%]="validation.value"></span></div></div>}</div></div><div class="panel"><div class="panel-title"><div><p class="eyebrow">CHANGE CONTROL</p><h2>Approval Center</h2></div><span class="badge badge-success">5 / 5 approved</span></div><ul class="approval-list">@for (approval of approvals; track approval.label) {<li><span class="material-icons">check_circle</span><span>{{approval.label}}</span><strong class="approved">{{approval.status}}</strong></li>}</ul></div></section>
      <section class="panel section-gap release-panel"><div class="panel-title"><div><p class="eyebrow">RELEASE CONTROL</p><h2>Release Readiness</h2></div><span class="badge badge-success">Ready for promotion</span></div><div class="release-grid"><div><span>Release name</span><strong>Northstar Platform Release</strong></div><div><span>Release version</span><strong>2026.09.17</strong></div><div><span>Build number</span><strong>build-4812</strong></div><div><span>Target environment</span><strong>QA1</strong></div><div><span>Deployment window</span><strong>18 Sep Â· 14:00 UTC</strong></div><div><span>Release manager</span><strong>Priya Shah</strong></div><div><span>Deployment risk</span><strong class="success-text">Low Â· 8%</strong></div></div></section>
      <section class="panel section-gap"><div class="panel-title"><div><p class="eyebrow">AUDIT READINESS</p><h2>Audit &amp; Compliance</h2></div><span class="badge badge-neutral">Evidence retained</span></div><div class="evidence-grid">@for (evidence of evidenceItems; track evidence.label) {<div><span class="material-icons">{{evidence.icon}}</span><strong>{{evidence.label}}</strong><span>{{evidence.detail}}</span><em>Complete</em></div>}</div></section>
      <section class="emergency-panel"><div><span class="material-icons">emergency</span><div><p class="eyebrow">EMERGENCY STOP</p><h2>Deployment Blockers</h2><p>Critical vulnerabilities, missing approvals, failed security gates, failed regression tests, and open secrets stop promotion automatically.</p></div></div><button class="btn btn-danger">View blockers</button></section>
      <section class="panel section-gap promotion-panel"><div class="panel-title"><div><p class="eyebrow">FINAL PROMOTION ACTIONS</p><h2>Promote Build</h2></div><span class="panel-description">Promotion is enabled only when all required checks pass.</span></div><div class="promotion-actions">@for (environment of promotionTargets; track environment) {<button class="btn btn-primary" [disabled]="environment === 'Production'"><span class="material-icons">arrow_forward</span>Promote to {{environment}}</button>}</div><p class="promotion-note"><span class="material-icons">info</span> Production promotion requires a completed security approval and mandatory validation evidence.</p></section>
    </div>
  `,
})
export class SecurityComponent implements OnInit {
  private readonly api = inject(ApiService); loading = false; error = false;
  readonly stages = [{ name: 'Code Scan', icon: 'check', tone: 'ready' }, { name: 'Remediation', icon: 'check', tone: 'ready' }, { name: 'Validation', icon: 'check', tone: 'ready' }, { name: 'RND', icon: 'check', tone: 'ready' }, { name: 'RND2', icon: 'check', tone: 'ready' }, { name: 'QA1', icon: 'check', tone: 'ready' }, { name: 'QA2', icon: 'pending', tone: 'review' }, { name: 'UAT', icon: 'lock', tone: 'pending' }, { name: 'Production', icon: 'lock', tone: 'pending' }];
  readonly kpis = [{ label: 'Applications ready for deployment', value: '18', note: '+4 this release', icon: 'apps', tone: 'success' }, { label: 'Current release version', value: '2026.09.17', note: 'Build 4812', icon: 'new_releases', tone: 'orange' }, { label: 'Passed security gates', value: '12 / 12', note: '100% complete', icon: 'verified', tone: 'success' }, { label: 'Open security findings', value: '24', note: '3 high Â· 0 critical', icon: 'shield', tone: 'warning' }, { label: 'Blocked deployments', value: '2', note: 'Needs attention', icon: 'block', tone: 'critical' }, { label: 'Approved exceptions', value: '7', note: '2 expire this week', icon: 'fact_check', tone: 'orange' }, { label: 'Production ready builds', value: '6', note: 'Across 4 applications', icon: 'rocket_launch', tone: 'success' }];
  readonly gates: Gate[] = ['Static Security Scan', 'Dependency Scan', 'Secrets Detection', 'Open Source Risk', 'Container Scan', 'Malware Scan', 'Code Signing Verification', 'SBOM Validation', 'API Security Validation', 'Infrastructure Security Validation', 'Configuration Validation', 'Compliance Validation'].map((name, index) => ({ name, status: index === 3 ? 'Review Required' : 'Passed', severity: index === 3 ? 'Medium' : index < 2 ? 'High' : 'Low', requirement: index === 3 ? 'Optional' : 'Required', result: index === 3 ? '2 licenses to review' : 'No issues found', reviewer: index % 3 === 0 ? 'A. Khan' : 'Automated', timestamp: '17 Sep Â· 13:' + String(40 - index).padStart(2, '0') + ' UTC' }));
  readonly blockers = [{ name: 'Critical Vulnerabilities', reason: 'None detected in current build', count: '0' }, { name: 'High Risk Secrets', reason: 'No exposed credentials detected', count: '0' }, { name: 'Known Exploitable Vulnerabilities', reason: 'Exploit intelligence is clear', count: '0' }, { name: 'Privilege Escalation Risks', reason: 'No escalation paths identified', count: '0' }, { name: 'Remote Code Execution Risks', reason: 'No RCE signatures detected', count: '0' }, { name: 'Security Policy Violations', reason: '2 informational policy notes', count: '0' }];
  readonly scores = [{ label: 'Code Security', value: 96 }, { label: 'Dependencies', value: 89 }, { label: 'Secrets', value: 100 }, { label: 'Compliance', value: 91 }, { label: 'Infrastructure', value: 88 }, { label: 'API Security', value: 94 }];
  readonly exceptions = [{ id: 'SEC-1045', app: 'Payment API', severity: 'Medium', reason: 'Vendor dependency upgrade scheduled', approved: 'M. Lee', expiration: '30 Sep 2026', status: 'Accepted Risk' }, { id: 'SEC-1038', app: 'Identity Service', severity: 'Low', reason: 'Confirmed false positive', approved: 'A. Khan', expiration: '15 Oct 2026', status: 'False Positive' }, { id: 'SEC-1029', app: 'Claims Service', severity: 'High', reason: 'Temporary mitigation in place', approved: 'P. Shah', expiration: '22 Sep 2026', status: 'Temporary Exception' }];
  readonly environments: Environment[] = [{ name: 'RND', state: 'Already Deployed', date: '17 Sep Â· 10:20', build: '4812', tone: 'deployed' }, { name: 'QA1', state: 'Ready for Deployment', date: 'â€”', build: '4812', tone: 'ready' }, { name: 'QA2', state: 'Ready for Deployment', date: 'â€”', build: '4812', tone: 'ready' }, { name: 'UAT', state: 'Blocked', date: 'â€”', build: '4798', tone: 'blocked' }, { name: 'PRODUCTION', state: 'Ready for Deployment', date: 'â€”', build: '4812', tone: 'ready' }];
  readonly validations = [{ label: 'Build Validation', value: 100 }, { label: 'Unit Test Validation', value: 98 }, { label: 'Integration Testing', value: 96 }, { label: 'Regression Testing', value: 94 }, { label: 'Security Testing', value: 100 }, { label: 'Performance Testing', value: 91 }, { label: 'Infrastructure Validation', value: 100 }, { label: 'Code Coverage', value: 87 }];
  readonly approvals = ['Security Review', 'Application Owner Review', 'Dev Lead Review', 'Architecture Review', 'Compliance Review'].map(label => ({ label, status: 'Approved' }));
  readonly evidenceItems = [{ label: 'Scan Reports', detail: '12 reports', icon: 'policy' }, { label: 'Validation Reports', detail: '8 reports', icon: 'fact_check' }, { label: 'Approval Records', detail: '5 records', icon: 'approval' }, { label: 'Exception Records', detail: '7 records', icon: 'gavel' }, { label: 'Deployment History', detail: '42 deployments', icon: 'history' }, { label: 'Compliance Mapping', detail: 'SOC 2 Â· ISO 27001', icon: 'account_balance' }];
  readonly promotionTargets = ['RND', 'QA1', 'QA2', 'UAT', 'Production'];
  ngOnInit(): void { this.load(); }
  load(): void { this.loading = true; this.error = false; this.api.metrics().subscribe({ next: () => this.loading = false, error: () => { this.loading = false; this.error = true; } }); }
}
