import { Component, inject } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { Router, RouterLink } from '@angular/router';
import { AuthService } from '../core/auth.service';

@Component({
  standalone: true,
  imports: [FormsModule, RouterLink],
  template: `<main class="login-page"><section class="login-brand"><span class="brand-mark">PNC</span><p class="eyebrow">Enterprise security operations</p><h1>Secure remediation, governed by design.</h1><p>Sign in to your tenant-scoped vulnerability workspace.</p></section><section class="login-card"><div class="card-logo">PNC <span>Vuln AI</span></div><h2>Welcome back</h2><p>Use a sample role account or your registered account.</p><form (ngSubmit)="signIn()"><label>Email<input class="field full" type="email" name="email" [(ngModel)]="email" required></label><label>Password<input class="field full" type="password" name="password" [(ngModel)]="password" required></label>@if(error){<p class="error">{{error}}</p>}<button class="sign-in" [disabled]="loading">{{loading ? 'Signing in…' : 'Sign in'}} <span>→</span></button></form><p class="auth-link">New user? <a routerLink="/register">Create an account</a></p><div class="local-note"><strong>Sample role logins</strong><br>Analyst: analyst@pnc.local / Analyst@123<br>Reviewer: reviewer@pnc.local / Reviewer@123<br>Admin: admin@pnc.local / Admin@123</div></section></main>`,
  styles: [`.login-page{display:grid;grid-template-columns:1fr 420px;gap:5rem;align-items:center;min-height:100vh;max-width:1100px;margin:auto;padding:2rem}.login-brand{color:#fff}.login-brand .brand-mark{display:grid;place-items:center;width:48px;height:48px;margin-bottom:2rem;color:var(--navy);background:var(--orange);border-radius:9px;font-size:.75rem;font-weight:800}.login-brand h1{max-width:580px;font-size:clamp(2rem,4vw,3.5rem)}.login-brand>p:not(.eyebrow){max-width:530px;color:#b8c9d9;line-height:1.7}.trust{display:flex;flex-wrap:wrap;gap:1rem;margin-top:2rem;color:#b8c9d9;font-size:.75rem}.login-card{padding:2.25rem;background:#fff;border-radius:14px;box-shadow:0 18px 45px rgba(0,0,0,.2)}.card-logo{color:var(--navy);font-weight:800;font-size:1.1rem}.card-logo span{color:var(--orange)}.login-card h2{margin:2.2rem 0 .45rem;font-size:1.6rem}.login-card p{color:var(--muted);line-height:1.6}.sign-in{display:flex;justify-content:space-between;align-items:center;width:100%;padding:1rem 1.1rem;margin:1.5rem 0;color:#fff;background:var(--orange);border-radius:7px;font-weight:700}.sign-in:hover{background:var(--orange-dark)}.login-card small{display:block;color:var(--muted);font-size:.7rem;line-height:1.5}.local-note{padding:.6rem;margin-top:1.5rem;color:#786000;background:#fff8d8;border-radius:6px;font-size:.7rem;text-align:center}@media(max-width:800px){.login-page{grid-template-columns:1fr;gap:2rem;max-width:500px}.login-brand h1{font-size:2rem}}`]
})
export class LoginComponent { private readonly auth = inject(AuthService); constructor(private readonly router: Router) {} email = 'analyst@pnc.local'; password = 'Analyst@123'; loading = false; error = ''; signIn(): void { this.loading = true; this.auth.login(this.email, this.password).subscribe({ next: () => this.router.navigateByUrl('/dashboard'), error: (e: { error?: { detail?: string } }) => { this.error = e.error?.detail || 'Unable to sign in.'; this.loading = false; } }); } }
