import { Component, inject } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { ApiService, EngineWorkflow, MvpFix, MvpScan, Vulnerability, WorkflowEvidence } from '../core/api.service';

@Component({
  standalone: true,
  imports: [FormsModule],
  template: `<div class="page"><div class="page-header"><div><p class="eyebrow">Discovery and remediation</p><h1>Scan code base</h1><p class="subtitle">Scan a local repository, classify findings, and prepare an auditable security change.</p></div><span class="badge badge-success">MVP enabled</span></div>
  <section class="panel scan-form"><div class="panel-title"><h2>Repository scan</h2><span class="badge badge-neutral">Custom Local SAST Scanner</span></div><div class="source-tabs"><button class="btn btn-ghost" [class.selected-tab]="source === 'local'" (click)="source = 'local'">Local path</button><button class="btn btn-ghost" [class.selected-tab]="source === 'git'" (click)="source = 'git'">Git URL</button><button class="btn btn-ghost" [class.selected-tab]="source === 'upload'" (click)="source = 'upload'">Upload ZIP</button></div>@if(source === 'local'){<label class="form-label">Repository path<input class="field full" [(ngModel)]="repositoryPath" placeholder="C:\\Projects\\Application1"></label>}@if(source === 'git'){<label class="form-label">Git repository URL<input class="field full" [(ngModel)]="repositoryUrl" placeholder="https://github.com/org/repository"></label>}@if(source === 'upload'){<label class="form-label">Repository ZIP archive<input class="field full" type="file" accept=".zip,application/zip" (change)="selectFile($event)"></label>@if(selectedFile){<p class="muted">Selected: {{selectedFile.name}}</p>}}<button class="btn btn-primary" [disabled]="loading" (click)="scan()">{{loading ? 'Scanning repository…' : 'Start scan'}}</button>@if(loading || workflowLoading){<p class="progress">{{scanStatus}}</p>}@if(error){<p class="error">{{error}}</p>}</section>
  @if(scanResult){<section class="panel result"><div class="panel-title"><div><p class="eyebrow">{{scanResult.status === 'COMPLETED' ? 'Scan completed' : 'Scan accepted'}}</p><h2>{{scanResult.application.name}}</h2></div><span class="badge badge-success">{{scanResult.findings.length}} findings</span></div><div class="result-grid"><div><small>Repository</small><strong>{{scanResult.application.repo_path}}</strong></div><div><small>Critical issues</small><strong>{{scanResult.application.critical_issues}}</strong></div><div><small>Scanner</small><strong>{{scanResult.scanner}}</strong></div></div></section>}
  @if(workflow){<section class="panel workflow-result"><div class="panel-title"><div><p class="eyebrow">Workflow status</p><h2>Security change progression</h2></div><span class="badge" [class.badge-success]="workflow.status === 'AWAITING_APPROVAL'" [class.badge-medium]="workflow.status !== 'AWAITING_APPROVAL'">{{workflow.status}}</span></div><p class="subtitle">Workflow {{workflow.workflow_id}} · Local mode reports planned or gated actions without creating external PRs or merging code.</p><div class="status-grid">@for(stage of workflowStages; track stage.name){<div class="status-card"><small>{{stage.name}}</small><strong>{{stage.status}}</strong></div>}</div></section>}
  @if(scanResult?.findings?.length){<section class="panel findings"><div class="panel-title"><h2>Findings</h2><span class="badge badge-neutral">Select a finding</span></div><div class="table-wrap"><table class="data-table"><thead><tr><th>Severity</th><th>Finding</th><th>Location</th><th>Risk</th><th>Actions</th></tr></thead><tbody>@for(row of scanResult!.findings; track row.id){<tr><td><span class="badge" [class.badge-critical]="row.severity==='CRITICAL'" [class.badge-high]="row.severity==='HIGH'" [class.badge-medium]="row.severity==='MEDIUM'" [class.badge-low]="row.severity==='LOW'">{{row.severity}}</span></td><td><strong>{{row.title}}</strong><small class="muted">{{row.description}}</small></td><td>{{row.file_name}}<small class="muted">Line {{row.line_number}}</small></td><td>{{row.risk_score}}</td><td><button class="btn btn-ghost" (click)="generate(row)">Generate fix</button> <button class="btn btn-ghost" (click)="jira(row)">Jira</button> <button class="btn btn-ghost" (click)="branch(row)">Branch</button> <button class="btn btn-primary" (click)="pullRequest(row)">Create Pull Request</button></td></tr>}</tbody></table></div></section>}
  @if(selected && fix){<section class="panel comparison"><div class="panel-title"><div><p class="eyebrow">AI remediation preview</p><h2>{{selected.title}}</h2></div><button class="btn btn-primary" (click)="pullRequest(selected)">Create pull request</button></div><p class="subtitle">{{fix.explanation}}</p><div class="code-grid"><div><h3>Before fix</h3><pre>{{fix.original_code}}</pre></div><div><h3>After fix</h3><pre>{{fix.fixed_code}}</pre></div></div><p class="success">{{message}}</p></section>}</div>`,
  styles: [`:host{display:block}.page{max-width:1200px;margin:auto}.page-header{display:flex;justify-content:space-between;gap:1rem;align-items:flex-start;margin-bottom:1.5rem}.subtitle{color:var(--muted);font-size:.9rem}.panel{padding:1.25rem;background:white;border:1px solid var(--line);border-radius:12px;box-shadow:0 5px 18px rgba(16,42,67,.04)}.panel-title{display:flex;justify-content:space-between;align-items:center;gap:1rem}.panel-title h2{margin:0}.form-label{display:block;margin:1rem 0;font-size:.8rem;font-weight:600}.full{display:block;width:100%;margin-top:.45rem}.progress{color:var(--navy);margin-top:1rem;font-weight:600}.error{color:var(--danger);margin-top:1rem}.success{color:var(--success);font-weight:600}.result,.workflow-result,.findings,.comparison{margin-top:1rem}.result-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:1rem}.result-grid div{padding:1rem;background:#f8fafc;border-radius:8px}.result-grid small,.result-grid strong{display:block}.result-grid small{color:var(--muted);font-size:.72rem}.result-grid strong{margin-top:.35rem;word-break:break-word}.status-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:.75rem}.status-card{padding:.85rem;background:#f8fafc;border:1px solid var(--line);border-radius:8px}.status-card small,.status-card strong{display:block}.status-card small{color:var(--muted);font-size:.72rem}.status-card strong{margin-top:.35rem;font-size:.82rem}.muted{display:block;margin-top:.25rem;color:var(--muted);font-size:.73rem}.code-grid{display:grid;grid-template-columns:1fr 1fr;gap:1rem}.code-grid pre{min-height:180px;max-height:360px;overflow:auto;padding:1rem;color:#e6edf3;background:#102a43;border-radius:8px;font:12px/1.55 Consolas,monospace;white-space:pre-wrap}@media(max-width:700px){.result-grid,.code-grid,.status-grid{grid-template-columns:1fr 1fr}}`],
})
export class ExecuteComponent {
  private readonly api = inject(ApiService);
  repositoryPath = ''; repositoryUrl = ''; selectedFile: File | null = null; source: 'local' | 'git' | 'upload' = 'local'; loading = false; workflowLoading = false; scanStatus = ''; error = ''; message = ''; scanResult: MvpScan | null = null; workflow: EngineWorkflow | null = null; selected: Vulnerability | null = null; fix: MvpFix | null = null;
  get workflowStages(): { name: string; status: string }[] { const evidence = this.workflow?.evidence || {}; return ['scan', 'classification', 'remediation', 'validation', 'test', 'pull_request', 'approval', 'merge'].map(name => { const value = evidence[name]; const stage = value && typeof value === 'object' ? value as WorkflowEvidence : undefined; return { name: name.replaceAll('_', ' '), status: stage?.status || 'NOT_REPORTED' }; }); }
  selectFile(event: Event): void { const input = event.target as HTMLInputElement; this.selectedFile = input.files?.[0] || null; }
  scan(): void { this.loading = true; this.workflowLoading = false; this.scanStatus = 'Scanning repository…'; this.error = ''; this.workflow = null; if (this.source === 'local' && !this.repositoryPath.trim()) { this.fail('Repository path is required.'); return; } if (this.source === 'git' && !this.repositoryUrl.trim()) { this.fail('Git repository URL is required.'); return; } if (this.source === 'upload' && !this.selectedFile) { this.fail('Choose a ZIP archive first.'); return; } const request = this.source === 'local' ? this.api.scanRepository(this.repositoryPath.trim()) : this.source === 'git' ? this.api.scanGitRepository(this.repositoryUrl.trim()) : this.api.scanUploadedRepository(this.selectedFile!); request.subscribe({ next: value => { this.scanResult = value; this.repositoryPath = value.application.repo_path; this.loading = false; this.workflowLoading = true; this.scanStatus = `Scan completed: ${value.findings.length} finding(s). Loading workflow evidence…`; this.api.createEngineWorkflow({ project: value.application.name, repository_path: value.application.repo_path, finding_ids: value.findings.map(finding => finding.id) }).subscribe({ next: workflow => { this.workflow = workflow; this.workflowLoading = false; this.scanStatus = `Scan and workflow completed (${workflow.status}).`; }, error: err => { this.workflowLoading = false; this.scanStatus = 'Scan completed. Workflow evidence is unavailable.'; this.error = err?.error?.detail || 'Scan completed, but workflow status could not be loaded. Findings remain available below.'; } }); }, error: err => { this.fail(err?.error?.detail || 'Scan failed. Verify the repository source and API status.'); } }); }
  private fail(message: string): void { this.error = message; this.loading = false; this.scanStatus = ''; }
  generate(row: Vulnerability): void { this.selected = row; this.message = ''; this.api.generateFix(row.id, this.repositoryPath).subscribe({ next: value => this.fix = value, error: err => this.error = err?.error?.detail || 'Fix generation failed.' }); }
  jira(row: Vulnerability): void { this.api.createJira(row.id).subscribe({ next: value => this.message = `Jira ticket ${value['ticket_number']} created.`, error: () => this.error = 'Jira ticket creation failed.' }); }
  branch(row: Vulnerability): void { this.api.createBranch(row.id, this.repositoryPath).subscribe({ next: value => this.message = `Branch ${value['branch_name']} created and committed locally.`, error: err => this.error = err?.error?.detail || 'Branch creation failed.' }); }
  pullRequest(row: Vulnerability): void { this.api.createPullRequest(row.id).subscribe({ next: value => this.message = `Pull request ${value['pr_number']} created.`, error: err => this.error = err?.error?.detail || 'Create a branch before opening a pull request.' }); }
}