import { Component, inject } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { ApiService, MvpFix, MvpScan, Vulnerability } from '../core/api.service';

@Component({
  standalone: true,
  imports: [FormsModule],
  template: `<div class="page"><div class="page-header"><div><p class="eyebrow">Discovery and remediation</p><h1>Scan code base</h1><p class="subtitle">Scan a local repository, classify findings, and prepare an auditable security change.</p></div><span class="badge badge-success">MVP enabled</span></div>
  <section class="panel scan-form"><div class="panel-title"><h2>Repository scan</h2><span class="badge badge-neutral">Semgrep / Bandit compatible</span></div><label class="form-label">Repository path<input class="field full" [(ngModel)]="repositoryPath" placeholder="C:\\Projects\\Application1"></label><button class="btn btn-primary" [disabled]="loading" (click)="scan()">{{loading ? 'Scanning repository…' : 'Start scan'}}</button>@if(error){<p class="error">{{error}}</p>}</section>
  @if(scanResult){<section class="panel result"><div class="panel-title"><div><p class="eyebrow">Scan completed</p><h2>{{scanResult.application.name}}</h2></div><span class="badge badge-success">{{scanResult.findings.length}} findings</span></div><div class="result-grid"><div><small>Repository</small><strong>{{scanResult.application.repo_path}}</strong></div><div><small>Critical issues</small><strong>{{scanResult.application.critical_issues}}</strong></div><div><small>Scanner</small><strong>{{scanResult.scanner}}</strong></div></div></section>}
  @if(scanResult?.findings?.length){<section class="panel findings"><div class="panel-title"><h2>Findings</h2><span class="badge badge-neutral">Select a finding</span></div><div class="table-wrap"><table class="data-table"><thead><tr><th>Severity</th><th>Finding</th><th>Location</th><th>Risk</th><th>Actions</th></tr></thead><tbody>@for(row of scanResult!.findings; track row.id){<tr><td><span class="badge" [class.badge-critical]="row.severity==='CRITICAL'" [class.badge-high]="row.severity==='HIGH'" [class.badge-medium]="row.severity==='MEDIUM'" [class.badge-low]="row.severity==='LOW'">{{row.severity}}</span></td><td><strong>{{row.title}}</strong><small class="muted">{{row.description}}</small></td><td>{{row.file_name}}<small class="muted">Line {{row.line_number}}</small></td><td>{{row.risk_score}}</td><td><button class="btn btn-ghost" (click)="generate(row)">Generate fix</button> <button class="btn btn-ghost" (click)="jira(row)">Jira</button> <button class="btn btn-ghost" (click)="branch(row)">Branch</button></td></tr>}</tbody></table></div></section>}
  @if(selected && fix){<section class="panel comparison"><div class="panel-title"><div><p class="eyebrow">AI remediation preview</p><h2>{{selected.title}}</h2></div><button class="btn btn-primary" (click)="pullRequest(selected)">Create pull request</button></div><p class="subtitle">{{fix.explanation}}</p><div class="code-grid"><div><h3>Before fix</h3><pre>{{fix.original_code}}</pre></div><div><h3>After fix</h3><pre>{{fix.fixed_code}}</pre></div></div><p class="success">{{message}}</p></section>}</div>`,
  styles: [`.scan-form{max-width:760px}.form-label{display:block;margin-bottom:1rem;font-size:.8rem;font-weight:600}.full{display:block;width:100%;margin-top:.45rem}.error{color:var(--danger);margin-top:1rem}.success{color:var(--success);font-weight:600}.result,.findings,.comparison{margin-top:1rem}.result-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:1rem}.result-grid div{padding:1rem;background:#f8fafc;border-radius:8px}.result-grid small,.result-grid strong{display:block}.result-grid small{color:var(--muted);font-size:.72rem}.result-grid strong{margin-top:.35rem;word-break:break-word}.muted{display:block;margin-top:.25rem;color:var(--muted);font-size:.73rem}.code-grid{display:grid;grid-template-columns:1fr 1fr;gap:1rem}.code-grid pre{min-height:180px;max-height:360px;overflow:auto;padding:1rem;color:#e6edf3;background:#102a43;border-radius:8px;font:12px/1.55 Consolas,monospace;white-space:pre-wrap}@media(max-width:700px){.result-grid,.code-grid{grid-template-columns:1fr}}`],
})
export class ExecuteComponent {
  private readonly api = inject(ApiService);
  repositoryPath = ''; loading = false; error = ''; message = ''; scanResult: MvpScan | null = null; selected: Vulnerability | null = null; fix: MvpFix | null = null;
  scan(): void { this.loading = true; this.error = ''; this.api.scanRepository(this.repositoryPath.trim()).subscribe({ next: value => { this.scanResult = value; this.loading = false; }, error: err => { this.error = err?.error?.detail || 'Scan failed. Verify the repository path and API status.'; this.loading = false; } }); }
  generate(row: Vulnerability): void { this.selected = row; this.message = ''; this.api.generateFix(row.id, this.repositoryPath).subscribe({ next: value => this.fix = value, error: err => this.error = err?.error?.detail || 'Fix generation failed.' }); }
  jira(row: Vulnerability): void { this.api.createJira(row.id).subscribe({ next: value => this.message = `Jira ticket ${value['ticket_number']} created.`, error: () => this.error = 'Jira ticket creation failed.' }); }
  branch(row: Vulnerability): void { this.api.createBranch(row.id, this.repositoryPath).subscribe({ next: value => this.message = `Branch ${value['branch_name']} created and committed locally.`, error: err => this.error = err?.error?.detail || 'Branch creation failed.' }); }
  pullRequest(row: Vulnerability): void { this.api.createPullRequest(row.id).subscribe({ next: value => this.message = `Pull request ${value['pr_number']} created.`, error: err => this.error = err?.error?.detail || 'Create a branch before opening a pull request.' }); }
}