CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE SCHEMA IF NOT EXISTS pnc;

CREATE OR REPLACE FUNCTION pnc.touch_modified_at() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN NEW.modified_at = now(); RETURN NEW; END $$;

CREATE TABLE pnc.tenants (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), name text NOT NULL UNIQUE, created_at timestamptz NOT NULL DEFAULT now(), modified_at timestamptz NOT NULL DEFAULT now(), created_by uuid, modified_by uuid, deleted_at timestamptz);
CREATE TABLE pnc.users (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL REFERENCES pnc.tenants(id), external_subject text NOT NULL, email text NOT NULL, display_name text NOT NULL, is_active boolean NOT NULL DEFAULT true, created_at timestamptz NOT NULL DEFAULT now(), modified_at timestamptz NOT NULL DEFAULT now(), created_by uuid, modified_by uuid, deleted_at timestamptz, UNIQUE(tenant_id, external_subject), UNIQUE(tenant_id, email));
CREATE TABLE pnc.roles (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid REFERENCES pnc.tenants(id), name text NOT NULL, description text, created_at timestamptz NOT NULL DEFAULT now(), modified_at timestamptz NOT NULL DEFAULT now(), created_by uuid, modified_by uuid, deleted_at timestamptz, UNIQUE(tenant_id, name));
CREATE TABLE pnc.permissions (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), name text NOT NULL UNIQUE, description text);
CREATE TABLE pnc.user_roles (user_id uuid NOT NULL REFERENCES pnc.users(id), role_id uuid NOT NULL REFERENCES pnc.roles(id), PRIMARY KEY(user_id, role_id));
CREATE TABLE pnc.role_permissions (role_id uuid NOT NULL REFERENCES pnc.roles(id), permission_id uuid NOT NULL REFERENCES pnc.permissions(id), PRIMARY KEY(role_id, permission_id));
CREATE TABLE pnc.mnemonics (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL REFERENCES pnc.tenants(id), code text NOT NULL, name text NOT NULL, owner_user_id uuid REFERENCES pnc.users(id), created_at timestamptz NOT NULL DEFAULT now(), modified_at timestamptz NOT NULL DEFAULT now(), created_by uuid, modified_by uuid, deleted_at timestamptz, UNIQUE(tenant_id, code));
CREATE TABLE pnc.applications (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL REFERENCES pnc.tenants(id), mnemonic_id uuid NOT NULL REFERENCES pnc.mnemonics(id), name text NOT NULL, criticality text NOT NULL DEFAULT 'MEDIUM', owner_user_id uuid REFERENCES pnc.users(id), created_at timestamptz NOT NULL DEFAULT now(), modified_at timestamptz NOT NULL DEFAULT now(), created_by uuid, modified_by uuid, deleted_at timestamptz, UNIQUE(mnemonic_id, name));
CREATE TABLE pnc.repositories (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL REFERENCES pnc.tenants(id), application_id uuid NOT NULL REFERENCES pnc.applications(id), provider text NOT NULL, external_id text NOT NULL, name text NOT NULL, clone_url text NOT NULL, default_branch text NOT NULL DEFAULT 'main', created_at timestamptz NOT NULL DEFAULT now(), modified_at timestamptz NOT NULL DEFAULT now(), created_by uuid, modified_by uuid, deleted_at timestamptz, UNIQUE(tenant_id, provider, external_id));
CREATE TABLE pnc.vulnerabilities (id uuid NOT NULL DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL REFERENCES pnc.tenants(id), repository_id uuid NOT NULL REFERENCES pnc.repositories(id), fingerprint text NOT NULL, title text NOT NULL, category text NOT NULL, cve text, cwe text, severity text NOT NULL, cvss numeric(4,2), status text NOT NULL DEFAULT 'OPEN', ai_confidence text NOT NULL DEFAULT 'MEDIUM', discovered_at timestamptz NOT NULL DEFAULT now(), fixed_at timestamptz, created_at timestamptz NOT NULL DEFAULT now(), modified_at timestamptz NOT NULL DEFAULT now(), created_by uuid, modified_by uuid, deleted_at timestamptz, PRIMARY KEY(id, discovered_at), UNIQUE(tenant_id, fingerprint, discovered_at)) PARTITION BY RANGE (discovered_at);
CREATE TABLE pnc.vulnerabilities_default PARTITION OF pnc.vulnerabilities DEFAULT;
CREATE INDEX ix_vuln_tenant_status_severity ON pnc.vulnerabilities (tenant_id, status, severity) WHERE deleted_at IS NULL;
CREATE INDEX ix_vuln_cve ON pnc.vulnerabilities (tenant_id, cve) WHERE cve IS NOT NULL AND deleted_at IS NULL;
CREATE TABLE pnc.remediation_actions (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL REFERENCES pnc.tenants(id), vulnerability_id uuid, action_type text NOT NULL, status text NOT NULL DEFAULT 'QUEUED', branch_name text, evidence jsonb NOT NULL DEFAULT '{}', created_at timestamptz NOT NULL DEFAULT now(), modified_at timestamptz NOT NULL DEFAULT now(), created_by uuid, modified_by uuid, deleted_at timestamptz);
CREATE TABLE pnc.approval_workflows (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL REFERENCES pnc.tenants(id), remediation_action_id uuid NOT NULL REFERENCES pnc.remediation_actions(id), status text NOT NULL DEFAULT 'PENDING', required_stages jsonb NOT NULL, completed_stages jsonb NOT NULL DEFAULT '[]', due_at timestamptz, created_at timestamptz NOT NULL DEFAULT now(), modified_at timestamptz NOT NULL DEFAULT now(), created_by uuid, modified_by uuid, deleted_at timestamptz);
CREATE TABLE pnc.pull_requests (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL REFERENCES pnc.tenants(id), repository_id uuid NOT NULL REFERENCES pnc.repositories(id), remediation_action_id uuid REFERENCES pnc.remediation_actions(id), provider text NOT NULL, external_id text NOT NULL, url text NOT NULL, status text NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), modified_at timestamptz NOT NULL DEFAULT now(), UNIQUE(tenant_id, provider, external_id));
CREATE TABLE pnc.deployments (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL REFERENCES pnc.tenants(id), application_id uuid NOT NULL REFERENCES pnc.applications(id), pull_request_id uuid REFERENCES pnc.pull_requests(id), environment text NOT NULL, status text NOT NULL, deployed_at timestamptz, rollback_reference text, created_at timestamptz NOT NULL DEFAULT now(), modified_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE pnc.audit_events (id bigint GENERATED ALWAYS AS IDENTITY, tenant_id uuid NOT NULL REFERENCES pnc.tenants(id), event_type text NOT NULL, aggregate_type text NOT NULL, aggregate_id uuid NOT NULL, actor_user_id uuid, payload jsonb NOT NULL DEFAULT '{}', occurred_at timestamptz NOT NULL DEFAULT now(), PRIMARY KEY(id, occurred_at)) PARTITION BY RANGE (occurred_at);
CREATE TABLE pnc.audit_events_default PARTITION OF pnc.audit_events DEFAULT;
CREATE INDEX ix_audit_tenant_time ON pnc.audit_events (tenant_id, occurred_at DESC);
CREATE INDEX ix_vulnerabilities_tenant_status ON pnc.vulnerabilities (tenant_id, status) WHERE deleted_at IS NULL;
CREATE INDEX ix_vulnerabilities_tenant_severity ON pnc.vulnerabilities (tenant_id, severity) WHERE deleted_at IS NULL;
CREATE INDEX ix_approval_workflows_tenant_status ON pnc.approval_workflows (tenant_id, status) WHERE deleted_at IS NULL;
CREATE TABLE pnc.knowledge_graph_nodes (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL REFERENCES pnc.tenants(id), node_type text NOT NULL, external_key text NOT NULL, properties jsonb NOT NULL DEFAULT '{}', embedding jsonb, UNIQUE(tenant_id, node_type, external_key));
CREATE TABLE pnc.knowledge_graph_edges (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL REFERENCES pnc.tenants(id), source_node_id uuid NOT NULL REFERENCES pnc.knowledge_graph_nodes(id), target_node_id uuid NOT NULL REFERENCES pnc.knowledge_graph_nodes(id), relationship text NOT NULL, properties jsonb NOT NULL DEFAULT '{}', UNIQUE(source_node_id, target_node_id, relationship));
CREATE TABLE pnc.compliance_evidence (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL REFERENCES pnc.tenants(id), framework text NOT NULL, control_id text NOT NULL, evidence_uri text NOT NULL, collected_at timestamptz NOT NULL DEFAULT now(), expires_at timestamptz, created_by uuid);

DO $$ DECLARE t text; BEGIN FOR t IN SELECT unnest(ARRAY['tenants','users','roles','mnemonics','applications','repositories','vulnerabilities','remediation_actions','approval_workflows','pull_requests','deployments']) LOOP EXECUTE format('CREATE TRIGGER %I_touch BEFORE UPDATE ON pnc.%I FOR EACH ROW EXECUTE FUNCTION pnc.touch_modified_at()', t, t); END LOOP; END $$;

ALTER TABLE pnc.users ENABLE ROW LEVEL SECURITY;
ALTER TABLE pnc.vulnerabilities ENABLE ROW LEVEL SECURITY;
ALTER TABLE pnc.audit_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE pnc.approval_workflows ENABLE ROW LEVEL SECURITY;
CREATE POLICY tenant_users ON pnc.users USING (tenant_id = nullif(current_setting('app.tenant_id', true), '')::uuid);
CREATE POLICY tenant_vulnerabilities ON pnc.vulnerabilities USING (tenant_id = nullif(current_setting('app.tenant_id', true), '')::uuid);
CREATE POLICY tenant_audit_events ON pnc.audit_events USING (tenant_id = nullif(current_setting('app.tenant_id', true), '')::uuid);
CREATE POLICY tenant_approval_workflows ON pnc.approval_workflows USING (tenant_id = nullif(current_setting('app.tenant_id', true), '')::uuid);
