import { Component } from '@angular/core';
import { RouterLink } from '@angular/router';

@Component({
  standalone: true,
  imports: [RouterLink],
  template: `<div class="page"><div class="page-header"><div><p class="eyebrow">Platform administration</p><h1>Enterprise operations</h1><p class="subtitle">Manage the connected security lifecycle from discovery through deployment and audit.</p></div><span class="badge badge-neutral">10 modules</span></div><div class="module-grid">@for(item of items;track item.name){<a class="module-card" [routerLink]="item.route || '/enterprise'"><span class="module-icon">{{item.icon}}</span><div><h2>{{item.name}}</h2><p>{{item.description}}</p><span class="module-link">{{item.route ? 'Open module →' : 'Coming online'}}</span></div></a>}</div></div>`,
  styles: [`.module-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(250px,1fr));gap:1rem}.module-card{display:flex;gap:1rem;padding:1.25rem;color:var(--ink);background:#fff;border:1px solid var(--line);border-radius:12px;text-decoration:none;transition:transform .15s,box-shadow .15s}.module-card:hover{transform:translateY(-2px);box-shadow:0 8px 20px rgba(16,42,67,.08)}.module-icon{display:grid;place-items:center;flex:0 0 40px;height:40px;color:var(--orange-dark);background:#fff1e7;border-radius:9px;font-size:1.1rem}.module-card h2{margin:.15rem 0 .4rem;font-size:.95rem}.module-card p{margin:0 0 .75rem;color:var(--muted);font-size:.76rem;line-height:1.5}.module-link{color:var(--orange-dark);font-size:.72rem;font-weight:700}`]
})
export class EnterpriseComponent {
  items = [{name:'Mnemonic management',icon:'⌘',description:'Organize business units and security ownership.',route:''},{name:'Application management',icon:'▦',description:'Maintain application criticality and service context.',route:''},{name:'Repository management',icon:'◈',description:'Connect source repositories and scanning status.',route:''},{name:'Pull request dashboard',icon:'↗',description:'Track generated fixes and review readiness.',route:'/approvals'},{name:'Deployment dashboard',icon:'▶',description:'Monitor governed changes across environments.',route:''},{name:'Compliance dashboard',icon:'✓',description:'Map remediation activity to control evidence.',route:''},{name:'Audit dashboard',icon:'◷',description:'Review durable, tenant-scoped activity history.',route:''},{name:'Knowledge graph',icon:'✦',description:'Explore relationships across applications and findings.',route:'/copilot'},{name:'Reports',icon:'▤',description:'Prepare executive and operational reporting.',route:'/dashboard'},{name:'Administration',icon:'⚙',description:'Configure access, policies, and platform settings.',route:''}];
}
