import { DatePipe } from '@angular/common';
import { Component, OnInit, inject } from '@angular/core';
import { ApiService, ApprovalItem } from '../core/api.service';

@Component({
  standalone: true,
  imports: [DatePipe],
  template: `<div class="page"><div class="page-header"><div><p class="eyebrow">Change governance</p><h1>Approval queue</h1><p class="subtitle">Review evidence and pending change decisions across your tenant.</p></div><button class="btn btn-secondary" (click)="load()">↻ Refresh queue</button></div><div class="metric-grid"><article class="metric-card"><span class="metric-label">Pending approvals</span><strong class="metric-value">{{items.length}}</strong><span class="metric-note">Requires attention</span></article><article class="metric-card"><span class="metric-label">Within SLA</span><strong class="metric-value">{{items.length}}</strong><span class="metric-note">No escalations</span></article><article class="metric-card"><span class="metric-label">Security gate</span><strong class="metric-value">Active</strong><span class="metric-note">No bypasses</span></article><article class="metric-card"><span class="metric-label">Evidence coverage</span><strong class="metric-value">100%</strong><span class="metric-note">Workflow required</span></article></div><section class="panel"><div class="panel-title"><h2>Items awaiting decision</h2><span class="badge badge-neutral">{{loading ? 'Loading…' : 'Live queue'}}</span></div>@if (!loading && !items.length) {<div class="empty-state"><strong>Your approval queue is clear</strong><p>New remediation workflows will appear here after validation.</p></div>} @else {<div class="table-wrap"><table class="data-table"><thead><tr><th>Finding</th><th>Scope</th><th>Approval level</th><th>Due</th><th>Status</th><th>Action</th></tr></thead><tbody>@for(item of items; track item.id){<tr><td><strong>{{item.title}}</strong><small class="muted">{{item.id}}</small></td><td>{{item.mnemonic}} · {{item.repository}}</td><td>{{item.level}}</td><td>{{item.due_at | date:'MMM d, y'}}</td><td><span class="badge badge-medium">{{item.status}}</span></td><td><button class="btn btn-primary" (click)="decide(item, 'APPROVE')">Approve</button> <button class="btn btn-ghost" (click)="decide(item, 'REJECT')">Reject</button></td></tr>}</tbody></table></div>}</section></div>`
})
export class ApprovalsComponent implements OnInit { private readonly api = inject(ApiService); items: ApprovalItem[] = []; loading = false; ngOnInit(): void { this.load(); } load(): void { this.loading = true; this.api.approvals().subscribe({ next: value => { this.items = value; this.loading = false; }, error: () => { this.items = []; this.loading = false; } }); } decide(item: ApprovalItem, decision: 'APPROVE' | 'REJECT'): void { this.api.decideApproval(item.id, decision).subscribe({ next: () => { this.items = this.items.filter(value => value.id !== item.id); }, error: () => { item.status = 'ERROR'; } }); } }
