import { Component, OnInit, inject } from '@angular/core';
import { DashboardMetrics, ApiService } from '../core/api.service';

@Component({ standalone: true, template: `<div class="page"><div class="page-header"><div><p class="eyebrow">Executive overview</p><h1>Security operations dashboard</h1><p class="subtitle">A tenant-scoped view of risk, remediation progress, and governed change activity.</p></div><button class="btn btn-secondary" (click)="load()">↻ Refresh data</button></div>@if (loading) {<div class="panel empty-state">Loading operational metrics…</div>} @else if (error) {<div class="panel empty-state">Metrics are temporarily unavailable. <button class="btn btn-ghost" (click)="load()">Try again</button></div>} @else {<section class="metric-grid">@for (metric of metricCards; track metric.label) {<article class="metric-card"><span class="metric-label">{{metric.label}}</span><strong class="metric-value">{{metric.value}}</strong><span class="metric-note">{{metric.note}}</span></article>}</section><div class="two-column"><section class="panel"><div class="panel-title"><h2>Risk posture</h2><span class="badge badge-neutral">Live inventory</span></div><div class="risk-row"><span>Critical</span><div class="progress"><span [style.width.%]="criticalPercent"></span></div><strong>{{metrics?.critical ?? 0}}</strong></div><div class="risk-row"><span>High</span><div class="progress"><span [style.width.%]="highPercent"></span></div><strong>{{metrics?.high ?? 0}}</strong></div><div class="risk-row"><span>Medium</span><div class="progress"><span [style.width.%]="mediumPercent"></span></div><strong>{{metrics?.medium ?? 0}}</strong></div><div class="risk-row"><span>Low</span><div class="progress"><span [style.width.%]="lowPercent"></span></div><strong>{{metrics?.low ?? 0}}</strong></div></section><section class="panel"><div class="panel-title"><h2>Remediation health</h2><span class="badge badge-success">Governed</span></div><p class="subtitle">AI-assisted remediation is gated by validation, security review, and change approval.</p><div class="health-score">{{metrics?.risk_reduction_percent ?? 0}}<small>% risk reduction</small></div><p class="subtitle">{{metrics?.remediated ?? 0}} findings remediated from the current tenant inventory.</p></section></div>}` , styles: [`.risk-row{display:grid;grid-template-columns:70px 1fr 55px;gap:.75rem;align-items:center;margin:1.1rem 0}.risk-row span,.risk-row strong{font-size:.78rem}.risk-row strong{text-align:right}.health-score{margin:1.5rem 0 .35rem;color:var(--orange);font-size:2.8rem;font-weight:700}.health-score small{display:block;color:var(--muted);font-size:.78rem;font-weight:500}`] })
export class DashboardComponent implements OnInit {
  private readonly api = inject(ApiService); metrics: DashboardMetrics | null = null; loading = false; error = false;
  get metricCards(): { label: string; value: string; note: string }[] { const m = this.metrics; return [{label:'Total findings',value:String(m?.total ?? 0),note:'Tenant inventory'}, {label:'Critical findings',value:String(m?.critical ?? 0),note:'Priority review'}, {label:'Remediated',value:String(m?.remediated ?? 0),note:'Change completed'}, {label:'AI success rate',value:`${m?.ai_success_rate_percent ?? 0}%`,note:'Validated workflows'}]; }
  get criticalPercent(): number { return this.percent(this.metrics?.critical); } get highPercent(): number { return this.percent(this.metrics?.high); } get mediumPercent(): number { return this.percent(this.metrics?.medium); } get lowPercent(): number { return this.percent(this.metrics?.low); }
  ngOnInit(): void { this.load(); } load(): void { this.loading = true; this.error = false; this.api.metrics().subscribe({next: value => { this.metrics = value; this.loading = false; }, error: () => { this.error = true; this.loading = false; }}); }
  private percent(value: number | undefined): number { const total = this.metrics?.total ?? 0; return total ? Math.max(4, Math.round((value ?? 0) / total * 100)) : 0; }
}
