import { Component } from '@angular/core';
import { RouterLink } from '@angular/router';

type Tone = 'critical' | 'high' | 'medium' | 'low' | 'success' | 'info';

@Component({
  standalone: true,
  imports: [RouterLink],
  styleUrls: ['./executive.component.scss'],
  template: `
    <div class="executive-page" [class.night-mode]="nightMode">
      <header class="exec-header">
        <div class="header-copy">
          <div class="eyebrow"><span class="pulse"></span> Executive risk &amp; governance command center</div>
          <h1>Organizational security posture</h1>
          <p>Board-ready visibility into risk, resilience, and governed security change.</p>
        </div>
        <div class="header-actions">
          <span class="live-status"><span class="live-dot"></span> Live · updated 2 min ago</span>
          <button class="icon-btn" type="button" (click)="nightMode = !nightMode" [attr.aria-label]="nightMode ? 'Use light theme' : 'Use dark theme'"><span class="material-icons">{{ nightMode ? 'light_mode' : 'dark_mode' }}</span></button>
          <button class="btn btn-secondary" type="button"><span class="material-icons">file_download</span> Export brief</button>
        </div>
      </header>

      <section class="filter-bar" aria-label="Dashboard filters">
        <div class="filter-context"><span class="material-icons">tune</span><strong>Portfolio view</strong><span class="divider"></span><span class="muted">All business units</span></div>
        <label><span>Date range</span><select><option>Last 90 days</option><option>Last quarter</option><option>Year to date</option></select></label>
        <label><span>Business unit</span><select><option>All business units</option><option>Retail Banking</option><option>Payments</option></select></label>
        <label><span>Severity</span><select><option>All severities</option><option>Critical &amp; High</option><option>Critical only</option></select></label>
        <button class="filter-reset" type="button"><span class="material-icons">refresh</span> Reset</button>
      </section>

      <section class="hero-grid">
        <article class="posture-hero panel">
          <div class="panel-heading"><div><span class="section-kicker">Enterprise posture</span><h2>Risk is trending down</h2></div><span class="badge badge-success"><span class="material-icons">south</span> 18% vs Q2</span></div>
          <div class="posture-body"><div class="score-ring"><div><strong>82</strong><small>/ 100</small><span>Security score</span></div></div><div class="commentary"><p class="quote">“Overall risk reduced by <strong>18%</strong> compared to last quarter.”</p><p>Remediation velocity is exceeding target across 7 of 9 business units. Two critical exposures require executive attention today.</p><div class="mini-meta"><span><i class="status-bar green"></i> Target <strong>85</strong></span><span><i class="status-bar orange"></i> Prior <strong>76</strong></span></div></div></div>
          <div class="hero-footer"><span><span class="material-icons">verified_user</span> No active security incidents</span><a routerLink="/security">View security operations <span class="material-icons">arrow_forward</span></a></div>
        </article>
        <article class="panel attention-panel"><div class="panel-heading"><div><span class="section-kicker">Executive attention</span><h2>What needs action</h2></div><span class="badge badge-critical">2 urgent</span></div><div class="attention-item"><span class="attention-icon critical"><span class="material-icons">priority_high</span></span><div><strong>Payment Gateway · CVE-2024-3094</strong><p>Critical exposure · SLA breach in 2 days</p></div><button class="text-action" type="button">Review</button></div><div class="attention-item"><span class="attention-icon warning"><span class="material-icons">gavel</span></span><div><strong>3 changes awaiting approval</strong><p>Manager review is blocking release</p></div><button class="text-action" routerLink="/approvals" type="button">Open queue</button></div><div class="attention-item"><span class="attention-icon info"><span class="material-icons">fact_check</span></span><div><strong>Q3 audit package is 91% ready</strong><p>14 evidence artifacts still missing</p></div><button class="text-action" type="button">Prepare</button></div></article>
      </section>

      <section class="kpi-grid" aria-label="Executive summary metrics">
        @for (kpi of kpis; track kpi.label) { <article class="kpi-card" [class]="'tone-' + kpi.tone"><div class="kpi-top"><span>{{ kpi.label }}</span><span class="material-icons">{{ kpi.icon }}</span></div><strong>{{ kpi.value }}</strong><div class="kpi-trend" [class.negative]="kpi.negative"><span class="material-icons">{{ kpi.negative ? 'north' : 'south' }}</span> {{ kpi.trend }} <small>vs previous period</small></div><div class="sparkline"><span [style.width.%]="kpi.progress"></span></div></article> }
      </section>

      <div class="content-grid">
        <article class="panel chart-panel risk-panel"><div class="panel-heading"><div><span class="section-kicker">Risk posture</span><h2>Risk distribution &amp; trend</h2></div><button class="icon-btn small"><span class="material-icons">more_horiz</span></button></div><div class="chart-layout"><div class="donut" aria-label="Risk distribution chart"><div><strong>1,284</strong><span>Total findings</span></div></div><div class="legend">@for (item of severity; track item.label) { <div><span class="legend-label"><i [class]="'dot ' + item.tone"></i>{{ item.label }}</span><strong>{{ item.count }}</strong><small>{{ item.percent }}%</small></div> }</div></div><div class="line-chart"><div class="chart-y"><span>1.4k</span><span>1.0k</span><span>600</span><span>200</span></div><svg viewBox="0 0 600 145" preserveAspectRatio="none" role="img" aria-label="Risk trend over six months"><defs><linearGradient id="area" x1="0" x2="0" y1="0" y2="1"><stop offset="0" stop-color="#ff7a1a" stop-opacity=".25"/><stop offset="1" stop-color="#ff7a1a" stop-opacity="0"/></linearGradient></defs><path class="area" d="M0,27 C70,32 85,44 130,48 S190,39 235,65 S305,61 350,78 S420,70 465,91 S535,92 600,113 V145 H0Z"/><path class="line" d="M0,27 C70,32 85,44 130,48 S190,39 235,65 S305,61 350,78 S420,70 465,91 S535,92 600,113"/><circle cx="600" cy="113" r="4"/></svg><div class="chart-x"><span>Apr</span><span>May</span><span>Jun</span><span>Jul</span><span>Aug</span><span>Sep</span></div></div><div class="category-list"><span>Top risk categories</span><div><b>Access control</b><i><em style="width:72%"></em></i><strong>284</strong></div><div><b>Data protection</b><i><em style="width:54%"></em></i><strong>198</strong></div><div><b>Supply chain</b><i><em style="width:38%"></em></i><strong>142</strong></div></div></article>

        <article class="panel governance-panel"><div class="panel-heading"><div><span class="section-kicker">Workflow governance</span><h2>Controlled change coverage</h2></div><span class="badge badge-success">On target</span></div><div class="coverage"><div class="coverage-number"><strong>89%</strong><span>Governance coverage</span></div><div class="coverage-ring"><span>89</span></div></div><div class="progress-track"><span style="width:89%"></span></div><div class="governance-stats"><div><strong>482</strong><span>Total workflows</span></div><div><strong>429</strong><span>Governed</span></div><div><strong>24</strong><span>Pending validation</span></div><div><strong>17</strong><span>Pending approval</span></div></div><div class="governance-callout"><span class="material-icons">info</span><span><strong>53 workflows outside governance</strong><small>Prioritize Payments and Customer Identity portfolios.</small></span></div></article>

        <article class="panel lifecycle-panel"><div class="panel-heading"><div><span class="section-kicker">Security workflow lifecycle</span><h2>From finding to closure</h2></div><button class="text-action" type="button">View all workflows <span class="material-icons">arrow_forward</span></button></div><div class="lifecycle">@for (stage of lifecycle; track stage.label; let last = $last) { <div class="life-stage"><span class="life-icon" [class.done]="stage.done"><span class="material-icons">{{ stage.icon }}</span></span><strong>{{ stage.count }}</strong><span>{{ stage.label }}</span>@if (!last) {<i class="connector" [class.complete]="stage.done"></i>}</div> }</div></article>

        <article class="panel remediation-panel"><div class="panel-heading"><div><span class="section-kicker">Remediation performance</span><h2>Teams are closing risk faster</h2></div><a routerLink="/remediation" class="text-action">Drill down <span class="material-icons">arrow_forward</span></a></div><div class="remediation-metrics"><div><strong>1,284</strong><span>Total findings</span></div><div><strong class="green-text">742</strong><span>Fixed / closed</span></div><div><strong>18.4d</strong><span>Mean time to remediate</span></div><div><strong class="red-text">36</strong><span>Overdue findings</span></div></div><div class="stacked-bar"><span class="fixed" style="width:58%"></span><span class="progressing" style="width:19%"></span><span class="open" style="width:23%"></span></div><div class="stacked-legend"><span><i class="dot success"></i>Fixed 58%</span><span><i class="dot info"></i>In progress 19%</span><span><i class="dot critical"></i>Open 23%</span><span class="trend-up"><span class="material-icons">south</span> 12% faster this quarter</span></div></article>

        <article class="panel compliance-panel"><div class="panel-heading"><div><span class="section-kicker">Compliance &amp; audit readiness</span><h2>Control posture</h2></div><button class="btn btn-ghost" type="button"><span class="material-icons">download</span> Audit package</button></div><div class="framework-grid">@for (framework of frameworks; track framework.name) { <div class="framework"><div class="framework-mark">{{ framework.short }}</div><div class="framework-copy"><strong>{{ framework.name }}</strong><span>{{ framework.controls }} controls covered</span></div><div class="framework-score"><strong>{{ framework.score }}%</strong><div class="mini-progress"><i [style.width.%]="framework.score"></i></div></div></div> }</div><div class="readiness-footer"><div><span>Audit readiness</span><strong>91%</strong></div><div><span>Evidence completeness</span><strong>96%</strong></div><div><span>Open control gaps</span><strong class="red-text">14</strong></div></div></article>

        <article class="panel approvals-panel"><div class="panel-heading"><div><span class="section-kicker">Security change governance</span><h2>Approval queue</h2></div><a routerLink="/approvals" class="text-action">Open queue <span class="material-icons">arrow_forward</span></a></div><div class="approval-summary"><div><strong>48</strong><span>Total changes</span></div><div><strong class="green-text">32</strong><span>Approved</span></div><div><strong class="orange-text">9</strong><span>Pending review</span></div><div><strong class="red-text">4</strong><span>Rejected</span></div><div><strong>3</strong><span>Emergency</span></div></div><div class="table-wrap"><table class="data-table"><thead><tr><th>Change</th><th>Application</th><th>Risk</th><th>Owner</th><th>Evidence</th></tr></thead><tbody>@for (change of changes; track change.id) {<tr><td><strong>{{ change.id }}</strong><small>{{ change.date }}</small></td><td>{{ change.app }}</td><td><span class="badge" [class]="'badge-' + change.tone">{{ change.risk }}</span></td><td>{{ change.owner }}</td><td><span class="evidence" [class.missing]="change.evidence !== 'Complete'"><span class="material-icons">{{ change.evidence === 'Complete' ? 'check_circle' : 'error' }}</span>{{ change.evidence }}</span></td></tr>}</tbody></table></div></article>
      </div>

      <section class="bottom-grid"><article class="insights panel"><div class="panel-heading"><div><span class="section-kicker">AI executive insights</span><h2>Signals that matter</h2></div><span class="ai-badge"><span class="material-icons">auto_awesome</span> AI assisted</span></div>@for (insight of insights; track insight.title) {<div class="insight"><span class="insight-icon" [class]="insight.tone"><span class="material-icons">{{ insight.icon }}</span></span><div><strong>{{ insight.title }}</strong><p>{{ insight.text }}</p></div><span class="confidence">{{ insight.confidence }}% <small>confidence</small></span></div>}</article><article class="quick panel"><div class="panel-heading"><div><span class="section-kicker">Executive shortcuts</span><h2>Quick actions</h2></div></div><div class="quick-grid"><a routerLink="/execute"><span class="material-icons">folder_scan</span><span>Scan code base</span></a><a routerLink="/remediation"><span class="material-icons">build_circle</span><span>Review remediation</span></a><a routerLink="/vulnerabilities"><span class="material-icons">bug_report</span><span>View findings</span></a><a routerLink="/approvals"><span class="material-icons">approval</span><span>Approval queue</span></a><button type="button"><span class="material-icons">inventory_2</span><span>Generate evidence</span></button><button type="button"><span class="material-icons">table_view</span><span>Export Excel</span></button></div></article></section>

      <footer class="dashboard-footer"><span><span class="material-icons">lock</span> Data is tenant-scoped and governed by role-based access.</span><span>Last full scan: Sep 18, 2026 · Next audit checkpoint: Oct 04, 2026</span></footer>
    </div>
  `
})
export class ExecutiveComponent {
  nightMode = false;
  kpis = [
    { label: 'Critical risks', value: '12', icon: 'priority_high', trend: '24%', progress: 18, tone: 'critical' as Tone, negative: false },
    { label: 'High risks', value: '86', icon: 'warning', trend: '11%', progress: 34, tone: 'high' as Tone, negative: false },
    { label: 'Open findings', value: '1,284', icon: 'bug_report', trend: '18%', progress: 58, tone: 'info' as Tone, negative: false },
    { label: 'Resolved findings', value: '742', icon: 'check_circle', trend: '32%', progress: 72, tone: 'success' as Tone, negative: false },
    { label: 'SLA compliance', value: '94.6%', icon: 'schedule', trend: '3.2%', progress: 94, tone: 'success' as Tone, negative: false },
    { label: 'Compliance score', value: '91%', icon: 'verified', trend: '5%', progress: 91, tone: 'info' as Tone, negative: false },
    { label: 'Governance coverage', value: '89%', icon: 'account_tree', trend: '7%', progress: 89, tone: 'info' as Tone, negative: false },
    { label: 'Business impact', value: '$2.4M', icon: 'shield', trend: '18%', progress: 63, tone: 'high' as Tone, negative: false },
  ];
  severity = [{ label: 'Critical', count: 12, percent: 1, tone: 'critical' }, { label: 'High', count: 86, percent: 7, tone: 'high' }, { label: 'Medium', count: 318, percent: 25, tone: 'medium' }, { label: 'Low', count: 868, percent: 67, tone: 'low' }];
  lifecycle = [{ label: 'Created', count: 1284, icon: 'add_circle', done: true }, { label: 'Classified', count: 1284, icon: 'category', done: true }, { label: 'Remediation', count: 1018, icon: 'build', done: true }, { label: 'Developer action', count: 742, icon: 'code', done: true }, { label: 'Validation', count: 528, icon: 'fact_check', done: true }, { label: 'Review', count: 214, icon: 'security', done: false }, { label: 'Approval', count: 96, icon: 'approval', done: false }, { label: 'Closed', count: 742, icon: 'task_alt', done: true }];
  frameworks = [{ name: 'ISO 27001', short: 'ISO', controls: 86, score: 94 }, { name: 'SOC 2', short: 'SOC', controls: 61, score: 96 }, { name: 'NIST CSF', short: 'NIST', controls: 98, score: 89 }, { name: 'CIS Controls', short: 'CIS', controls: 72, score: 87 }];
  changes = [{ id: 'CHG-10428', date: 'Today, 09:42', app: 'Payment Gateway', risk: 'High', tone: 'high', owner: 'A. Rodriguez', evidence: 'Complete' }, { id: 'CHG-10421', date: 'Yesterday, 16:18', app: 'Identity Platform', risk: 'Medium', tone: 'medium', owner: 'K. Patel', evidence: 'Missing' }, { id: 'CHG-10417', date: 'Sep 16, 14:03', app: 'Mobile Banking', risk: 'Critical', tone: 'critical', owner: 'J. Chen', evidence: 'Complete' }];
  insights = [{ title: 'Payment services have the highest exposure', text: 'Critical and high findings are concentrated in 3 payment applications. Prioritize CHG-10428 before the next release window.', icon: 'trending_up', tone: 'critical', confidence: 96 }, { title: 'Remediation performance is strongest in Retail', text: 'Retail Engineering is closing findings 2.4× faster than the portfolio average. Reuse their workflow playbook.', icon: 'groups', tone: 'success', confidence: 91 }, { title: 'Audit evidence gap is narrowing', text: 'Evidence completeness improved 8% this month. Fourteen control gaps still need an accountable owner.', icon: 'lightbulb', tone: 'info', confidence: 88 }];
}